version: "0.0.1"
normal-items:
  DIAMOND_SWORD:
    name: "<gold>Holy Shit, A Diamond Sword"
    lore:
    - "<gold>Fuck yeah, lore!"
recipes:
  DIAMOND_SWORD:
    name: "<gold>Holy Fuck, A Diamond Sword"
    lore:
    - "<gold>Fuck yeah, more lore!"
    recipe:
    - ' x '
    - ' x '
    - ' y '
    ingredients:
      x: DIAMOND
      y: DIAMOND_SWORD